In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)  # Creating numpy array from a python object such as a list

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

5 Mechanisms for creating arrays :

1- Conversion from other Python structures (e.g. lists,tuples)
2- Intrinsic numpy array creation objects(e.g. arange,ones,zeros,etc.)
3- Reading arrays from disk,either from standard or custom formats
4- Creating arrays from raw bytes through the use of strings or buffers
5- Use of special library functions(e.g. random) 

# Array Creation: Conversion from other Python structures

In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,21})   # dictionary

array({34, 21, 23}, dtype=object)

# Array Creation : Intrinsic numpy array creation objects

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [19]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,4) # (first element, last element, number of elements)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
emp = np.empty((4,6))  # gives an empty array full of random elements
emp

array([[7.29290906e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304, 7.74860419e-304],
       [7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
        7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [23]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
ide = np.identity(45)        # gives an identity matrix
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr = arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr = arr.ravel()    # arr changed to 1-D again
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.shape   #1-D

(99,)

In [31]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar.sum(axis = 0)     # sums the elements vertically 

array([12,  8,  9])

In [33]:
ar.sum(axis = 1)     # sums the elements horizontally

array([ 6, 15,  8])

In [34]:
ar.T   # can transpose your array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [35]:
ar.flat

In [36]:
for item in ar.flat:  # one can iterate elements of the array using 'flat' attribute   
    print(item)

1
2
3
4
5
6
7
1
0


In [37]:
ar.ndim      # gives the dimensions of your array

2

In [38]:
ar.size

9

In [39]:
ar.nbytes   # gives the total number of bytes consumed by the elements of an array

36

In [44]:
one = np.array([1,3,4,634,2])

In [45]:
one.argmax()    # gives the index of the maximum element in the array

3

In [46]:
one.argmin()    # gives the index of the minimum element in the array

0

In [47]:
one.argsort()   # gives the indices in sorted order (ascending)


array([0, 4, 1, 2, 3], dtype=int64)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.argmin()   #gives the index of the min element in ar

8

In [49]:
ar.argmax()   #gives the index of the max element in ar

6

In [50]:
ar.argmax(axis = 0)  #gives the index of the max element vertically at axis = 0

array([2, 1, 1], dtype=int64)

In [53]:
ar.argmax(axis = 1)  # gives the index of the max element horizontally at axis = 1 

array([2, 2, 0], dtype=int64)

In [54]:
ar.argsort(axis = 0)  # gives the indices in sorted ascending order vertically

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [55]:
ar.argsort(axis = 1)  # gives the indices in sorted ascending order horizontally

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [56]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar.reshape(9,)   # (9, ) = (9,0); 0 is never mentioned inside parenthesis

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [59]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [62]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])  # creating another array(matrix) of elements
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [61]:
ar + ar2   # addition of both matrices

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [63]:
ar * ar2    # multiplication of both matrices

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [64]:
np.sqrt(ar)   # taking out square root of each element of ar

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [65]:
ar.sum()   # suming up the elements of ar 

29

In [66]:
ar.max()   # getting the maximum element present in ar

7

In [67]:
ar.min()   # getting the minimum element present in ar

0

In [68]:
np.where(ar > 5)    # to find an element by specifying a condition

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [69]:
type(np.where(ar > 5))

tuple

In [70]:
np.count_nonzero(ar)   # to count all the non-zero elements in an array

8

In [71]:
np.nonzero(ar)   # gives the index of each non-zero element in ar,where first array in output = rows & second array in output = columns 

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [72]:
ar[1,2] = 0

In [73]:
np.nonzero(ar)   # now (1,2) will not be shown in output since we have changed the element at (1,0) to 0.Previously, it was 6 & now, it is 0.

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [74]:
import sys

In [75]:
py_ar = [0,4,55,2]   # py_ar = python array(just a variable name). Here, is a list

In [76]:
np_ar = np.array(py_ar)    # np_ar = numpy array(just a variable name)

In [77]:
sys.getsizeof(1) * len(py_ar)   # size of 1 element multiplied by number of elements in the py_ar.The space occupied is more.

112

In [78]:
np_ar.itemsize * np_ar.size   # size of 1 item multiplied by the size of an array.The space occupied is very less.

16

In [79]:
np_ar.tolist()    # converts a numpy array to a python list

[0, 4, 55, 2]